services:
  sishc:
    image: ghcr.io/lanjelin/sishc:latest
    container_name: sishc
    environment:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - ./config:/config
      # - ~/.ssh/id_rsa:/config/.ssh/id_rsa:ro
    ports:
      - 5000:5000
    restart: unless-stopped
